# Generated by Django 4.2.30 on 2026-09-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='字段名')),
                ('ordinal_position', models.PositiveIntegerField(default=1, verbose_name='序号')),
                ('data_type', models.CharField(max_length=100, verbose_name='数据类型')),
                ('column_type', models.CharField(blank=True, default='', max_length=255, verbose_name='完整类型')),
                ('column_default', models.TextField(blank=True, null=True, verbose_name='默认值')),
                ('is_nullable', models.BooleanField(default=True, verbose_name='可空')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大长度')),
                ('numeric_precision', models.PositiveIntegerField(blank=True, null=True, verbose_name='精度')),
                ('numeric_scale', models.PositiveIntegerField(blank=True, null=True, verbose_name='小数位')),
                ('comment', models.TextField(blank=True, default='', verbose_name='字段注释')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '元数据字段',
                'verbose_name_plural': '元数据字段',
                'ordering': ['ordinal_position'],
            },
        ),
        migrations.CreateModel(
            name='MetadataConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='约束名')),
                ('constraint_type', models.CharField(max_length=50, verbose_name='约束类型')),
                ('column_names', models.JSONField(blank=True, default=list, verbose_name='约束字段')),
                ('referenced_table', models.CharField(blank=True, default='', max_length=200, verbose_name='引用表')),
                ('referenced_column', models.CharField(blank=True, default='', max_length=200, verbose_name='引用字段')),
                ('definition', models.TextField(blank=True, default='', verbose_name='约束定义')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '元数据约束',
                'verbose_name_plural': '元数据约束',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetadataDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='名称')),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL')], default='postgresql', max_length=50, verbose_name='数据库类型')),
                ('host', models.CharField(max_length=255, verbose_name='主机')),
                ('port', models.PositiveIntegerField(default=3306, verbose_name='端口')),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('database_name', models.CharField(max_length=200, verbose_name='数据库名')),
                ('schema_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Schema')),
                ('status', models.CharField(choices=[('pending', '未同步'), ('synced', '已同步'), ('error', '同步失败')], default='pending', max_length=20, verbose_name='同步状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '元数据库',
                'verbose_name_plural': '元数据库',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=200, verbose_name='Schema')),
                ('name', models.CharField(max_length=200, verbose_name='表名')),
                ('table_type', models.CharField(blank=True, default='', max_length=50, verbose_name='表类型')),
                ('comment', models.TextField(blank=True, default='', verbose_name='表注释')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='common.metadatadatabase', verbose_name='元数据库')),
            ],
            options={
                'verbose_name': '元数据表',
                'verbose_name_plural': '元数据表',
                'ordering': ['schema_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetadataIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='索引名')),
                ('is_unique', models.BooleanField(default=False, verbose_name='唯一索引')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主键索引')),
                ('column_names', models.JSONField(blank=True, default=list, verbose_name='索引字段')),
                ('definition', models.TextField(blank=True, default='', verbose_name='索引定义')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='common.metadatatable', verbose_name='所属表')),
            ],
            options={
                'verbose_name': '元数据索引',
                'verbose_name_plural': '元数据索引',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='metadatadatabase',
            constraint=models.UniqueConstraint(fields=('db_type', 'host', 'port', 'database_name'), name='uniq_metadata_remote_db'),
        ),
        migrations.AddField(
            model_name='metadataconstraint',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='common.metadatatable', verbose_name='所属表'),
        ),
        migrations.AddField(
            model_name='metadatacolumn',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='common.metadatatable', verbose_name='所属表'),
        ),
        migrations.AddConstraint(
            model_name='metadatatable',
            constraint=models.UniqueConstraint(fields=('database', 'schema_name', 'name'), name='uniq_metadata_table'),
        ),
        migrations.AddConstraint(
            model_name='metadataindex',
            constraint=models.UniqueConstraint(fields=('table', 'name'), name='uniq_metadata_index'),
        ),
        migrations.AddConstraint(
            model_name='metadataconstraint',
            constraint=models.UniqueConstraint(fields=('table', 'name'), name='uniq_metadata_constraint'),
        ),
        migrations.AddConstraint(
            model_name='metadatacolumn',
            constraint=models.UniqueConstraint(fields=('table', 'name'), name='uniq_metadata_column'),
        ),
    ]
