# Generated by Django 4.2.30 on 2026-09-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('hive', 'Hive'), ('doris', 'Doris'), ('sqlserver', 'SQL Server'), ('kafka', 'Kafka'), ('other', '其他')], default='mysql', max_length=50, verbose_name='类型')),
                ('jdbc_url', models.CharField(blank=True, default='', max_length=1000, verbose_name='JDBC URL')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='主机')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='端口')),
                ('database_name', models.CharField(blank=True, default='', max_length=200, verbose_name='数据库/服务名')),
                ('schema_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Schema')),
                ('username', models.CharField(blank=True, default='', max_length=200, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=500, verbose_name='密码')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '元数据源配置',
                'verbose_name_plural': '元数据源配置',
                'ordering': ['db_type', 'name'],
            },
        ),
    ]
