# Generated by Django 4.2.30 on 2026-09-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_metadatasourceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineageEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(max_length=500, verbose_name='源表')),
                ('target_table', models.CharField(max_length=500, verbose_name='目标表')),
                ('sql_file', models.CharField(blank=True, default='', max_length=500, verbose_name='来源 SQL 文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '血缘关系',
                'verbose_name_plural': '血缘关系',
                'ordering': ['target_table', 'source_table'],
            },
        ),
        migrations.CreateModel(
            name='ReconcileTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='任务名')),
                ('task_type', models.CharField(choices=[('row_count', '行数对账'), ('pk_snapshot', '主键快照对账'), ('field_value', '字段值对账'), ('metric', '业务指标对账'), ('metadata', '元数据对账')], max_length=30, verbose_name='对账类型')),
                ('source_db_name', models.CharField(blank=True, default='', max_length=200, verbose_name='源库名')),
                ('source_schema', models.CharField(blank=True, default='', max_length=200, verbose_name='源 Schema(PG)')),
                ('target_db_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Doris 目标库')),
                ('tables', models.JSONField(blank=True, default=list, verbose_name='对账表')),
                ('columns', models.JSONField(blank=True, default=list, verbose_name='字段值对账列')),
                ('pk_columns', models.JSONField(blank=True, default=list, verbose_name='主键快照主键列')),
                ('metric_sql', models.TextField(blank=True, default='', verbose_name='指标 SQL({table} 占位)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconcile_tasks', to='common.metadatasourceconfig', verbose_name='源配置')),
            ],
            options={
                'verbose_name': '对账任务',
                'verbose_name_plural': '对账任务',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconcileRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='汇总')),
                ('details', models.JSONField(blank=True, default=list, verbose_name='明细')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时 ms')),
                ('ran_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='common.reconciletask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '对账执行',
                'verbose_name_plural': '对账执行',
                'ordering': ['-ran_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='lineageedge',
            constraint=models.UniqueConstraint(fields=('source_table', 'target_table', 'sql_file'), name='uniq_lineage_edge'),
        ),
    ]
