# Generated by Django 4.2.30 on 2026-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_lineageedge_reconciletask_reconcilerun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='request', max_length=20, verbose_name='事件类型')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='方法')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='路径')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='状态码')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时 ms')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='用户')),
                ('ip', models.CharField(blank=True, default='', max_length=64, verbose_name='IP')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '埋点事件',
                'verbose_name_plural': '埋点事件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='common_anal_created_808a0a_idx'), models.Index(fields=['path'], name='common_anal_path_699c33_idx'), models.Index(fields=['status_code'], name='common_anal_status__157eb6_idx')],
            },
        ),
    ]
