# Generated by Django 4.2.30 on 2026-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_analyticsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_path', models.CharField(max_length=500, verbose_name='脚本路径')),
                ('args', models.JSONField(blank=True, default=list, verbose_name='参数')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='退出码')),
                ('output', models.TextField(blank=True, default='', verbose_name='输出')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时 ms')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
            ],
            options={
                'verbose_name': '脚本运行',
                'verbose_name_plural': '脚本运行',
                'ordering': ['-started_at'],
            },
        ),
    ]
