# Generated by Django 4.2.30 on 2026-09-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_scriptrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='任务名')),
                ('job_type', models.CharField(choices=[('script', '脚本'), ('etl', 'ETL')], default='script', max_length=20, verbose_name='类型')),
                ('script_path', models.CharField(blank=True, default='', max_length=500, verbose_name='脚本路径')),
                ('args', models.JSONField(blank=True, default=list, verbose_name='参数')),
                ('cron_minute', models.PositiveIntegerField(default=0, verbose_name='分')),
                ('cron_hour', models.PositiveIntegerField(default=2, verbose_name='时')),
                ('timeout_seconds', models.PositiveIntegerField(default=900, verbose_name='超时秒')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '调度任务',
                'verbose_name_plural': '调度任务',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='退出码')),
                ('output', models.TextField(blank=True, default='', verbose_name='输出')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时 ms')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='common.schedulerjob', verbose_name='任务')),
            ],
            options={
                'verbose_name': '调度执行',
                'verbose_name_plural': '调度执行',
                'ordering': ['-started_at'],
            },
        ),
    ]
