# Generated by Django 4.2.30 on 2026-09-03 11:58

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_schedulerjob_schedulerrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatadatabase',
            name='db_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('odps', 'MaxCompute(ODPS)')], default='postgresql', max_length=50, verbose_name='数据库类型'),
        ),
        migrations.AlterField(
            model_name='metadatasourceconfig',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('hive', 'Hive'), ('doris', 'Doris'), ('sqlserver', 'SQL Server'), ('kafka', 'Kafka'), ('odps', 'MaxCompute(ODPS)'), ('other', '其他')], default='mysql', max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='metadatasourceconfig',
            name='password',
            field=common.fields.EncryptedCharField(blank=True, default='', max_length=1000, verbose_name='密码'),
        ),
    ]
