# Generated by Django 4.2.30 on 2026-09-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_metadatadatabase_db_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatadatabase',
            name='db_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oceanbase', 'OceanBase'), ('gaussdb', 'GaussDB'), ('dws', 'GaussDB(DWS)'), ('odps', 'MaxCompute(ODPS)')], default='postgresql', max_length=50, verbose_name='数据库类型'),
        ),
        migrations.AlterField(
            model_name='metadatasourceconfig',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('hive', 'Hive'), ('doris', 'Doris'), ('sqlserver', 'SQL Server'), ('kafka', 'Kafka'), ('oceanbase', 'OceanBase'), ('gaussdb', 'GaussDB'), ('dws', 'GaussDB(DWS)'), ('odps', 'MaxCompute(ODPS)'), ('other', '其他')], default='mysql', max_length=50, verbose_name='类型'),
        ),
    ]
