# Generated by Django 4.2.30 on 2026-09-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_metadatadatabase_db_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatadatabase',
            name='db_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle'), ('oceanbase', 'OceanBase'), ('gaussdb', 'GaussDB'), ('dws', 'GaussDB(DWS)'), ('odps', 'MaxCompute(ODPS)')], default='postgresql', max_length=50, verbose_name='数据库类型'),
        ),
    ]
